#!/bin/zsh
# Aliases
#
# editors
alias v="nvim"
alias em="/usr/bin/emacs -nw"

alias cd="z"

# doble dot
alias ..="cd .."

# Listing
alias ls="lsd"
alias ll="lsd -la"
alias l="lsd -la"
alias la="lsd -A"

# Colorize grep output
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color auto"

# Miselaneous
alias cat="bat"
alias install="sudo pacman -Sy"
alias update="sudo pacman -Syyu"
alias yayinstall="yay -S"
alias pf="pfetch"

# dotfiles
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

# tmux attach
# alias ta='tmux attach'

# trash
alias rm='rmtrash'
alias rmdir='rmdirtrash'
alias sudo='sudo '

# yt-dlp
alias yta-aac="yt-dlp --extract-audio --audio-format aac "
alias yta-best="yt-dlp --extract-audio --audio-format best "
alias yta-flac="yt-dlp --extract-audio --audio-format flac "
alias yta-m4a="yt-dlp --extract-audio --audio-format m4a "
alias yta-mp3="yt-dlp --extract-audio --audio-format mp3 "
alias yta-opus="yt-dlp --extract-audio --audio-format opus "
alias yta-vorbis="yt-dlp --extract-audio --audio-format vorbis "
alias yta-wav="yt-dlp --extract-audio --audio-format wav "
alias ytv-best="yt-dlp -f bestvideo+bestaudio "

#video and image viwers
alias mpv="devour mpv"
alias sxiv="devour sxiv"

#lf
alias lf="lf-ueberzug"

