#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DVI-I-0 -d 1 2 3 4 5
bspc monitor VGA1 -d 6 7 8 9 0

bspc config border_width         1
bspc config border_radius        10
bspc config focused_border_color  "#74c7ec"
bspc config window_gap           0
bspc config focus_follows_pointer true
bspc config automatic_scheme spiral
bspc config initial_polarity first_child

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle       true
bspc config pointer_follows_monitor     true

/home/santorar/.screenlayout/screens.sh &
# app rules
# spawn in a specific desktop
bspc rule -a Gimp-2.10 desktop='^8' state=floating follow=on
bspc rule -a Bitwarden state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Min desktop='^6' follow=on
bspc rule -a Signal desktop='^7' follow=on

# default floating

bspc rule -a floatterminal state=floating
bspc rule -a st-256color:stfloat state=floating follow=on
bspc rule -a tfloat:tfloat state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a mplayer2 state=floating
bspc rule -a Qalculate-gtk state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

/home/santorar/.config/polybar/launch.sh &
dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
setxkbmap -option caps:super,altwin:menu_win -layout us -variant altgr-intl &
killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape' &
xset -q | grep "Caps Lock:\s*on" && xdotool key Caps_Lock &
xset r rate 300 50 &
nitrogen --restore &
playerctld &
picom &
parcellite &
wmname "LG3D"
