#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DVI-I-0 -d 1 2 3 4 5
bspc monitor VGA-1-1 -d 6 7 8 9 0

bspc config border_width         2
bspc config focused_border_color  "#8BCAD9"
bspc config window_gap           3
bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config pointer_follows_monitor     true

# app rules
# spawn in a specific desktop
bspc rule -a Gimp-2.10 desktop='^8' state=floating follow=on
bspc rule -a Code desktop='^2'
bspc rule -a Brave-browser desktop='^6' follow=on
bspc rule -a Signal desktop='^7' follow=on

# default floating

bspc rule -a floatterminal state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a gnome-calculator state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

/home/santorar/.config/polybar/launch.sh &
redshift-gtk -l 4.25:-74.18333 &
flameshot &
spotify &
