#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DVI-I-0 -d I II III IV V
bspc monitor VGA-1-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config focused_border_color  "#8BCAD9"
bspc config window_gap           5
bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a brave desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a gnome-calculator state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

/home/santorar/.config/polybar/launch.sh &
redshift-gtk -l 4.25:-74.18333 &
